### ISSUE TITLE
Attribute Error

### ISSUE THREAD

**Issue by WebTheDev** [kajchang/StudentVue#12]
I'm getting this error when I try to login:
Traceback (most recent call last):
  File "XXXX", line 2, in <module>
    sv = StudentVue('username', 'password', 'domain')
  File "C:\XXXX\XXXXX\AppData\Local\Programs\Python\Python37\lib\site-packages\studentvue\studentvue.py", line 35, in __init__
    form_data = helpers.parse_form(login_page.find(id='aspnetForm'))
  File "C:\XXXX\XXXXX\AppData\Local\Programs\Python\Python37\lib\site-packages\studentvue\helpers.py", line 11, in parse_form
    keys = [input_['name'] for input_ in form.find_all('input')] + \
AttributeError: 'NoneType' object has no attribute 'find_all'

**Comment by kaijchang** [comment]
@RealWEBSURFER5 this is an error with locating the login form on the login page. If you share your portal domain, I can take a look.

**Comment by WebTheDev** [comment]
@kajchang Sure! Mind if I send it over discord to you?

**Comment by kaijchang** [comment]
@RealWEBSURFER5 yeah kachang#2951

**Comment by kaijchang** [comment]
The problem was the district still being on an old version of StudentVue.

I published an old version of this library that should work for the old version of StudentVue and added references to the library in the README and when an `AttributeError` is tripped on login.
