### ISSUE TITLE
Version 2.0.1 breaks it

### ISSUE THREAD

**Issue by rishipudipeddi** [kajchang/StudentVue#14]
![image](https://user-images.githubusercontent.com/49598383/77564199-905ae780-6e7f-11ea-9404-514341303bbb.png)
@kajchang It works completely fine with version 1.3.2, but get_calendar() is apparently not n object in that version

**Comment by kaijchang** [comment]
@thexpiredpear this looks like an underlying problem with how dependencies are installed and not one that's caused by this package. This thread might have some fixes / insight: https://github.com/kdmurray91/SRApy/issues/1

**Comment by rishipudipeddi** [comment]
@kajchang No longer getting the dependency issue thanks to the stackoverflow answer, but now I'm getting an AttributeError instead 
![image](https://user-images.githubusercontent.com/49598383/77572371-1715c180-6e8c-11ea-8c68-5e67079b7ece.png)

**Comment by kaijchang** [comment]
2.0.0+ is incompatible with 1.x.x. Some of the function names changed, but also the return format changed significantly.

If you want to use 2.0.0+, which is significantly faster than 1.x.x, you're going to have to rewrite some code to make it compatible with the new format.

You can see some docs [here](https://studentvue-community.github.io/StudentVue/StudentVue.html).

```python
gradebook = sv.get_gradebook()
current_grades = gradebook['Gradebook']['Courses']['Course']
reporting_periods = gradebook['Gradebook']['ReportingPeriods']['ReportPeriod']
```

`current_grades` would be the grades for the current reporting period, while `reporting_periods` would hold the list of reporting periods that you get grades for.

To get grades for a specific reporting period, call `sv.get_gradebook()` with the reporting period's index as a argument.

```json
{
        "@Index": 0,
        "@GradePeriod": "P1",
        "@StartDate": "8/19/2019",
        "@EndDate": "9/27/2019"
}
```

For example, for me, if I wanted to get the gradebook for P1, I would do `sv.get_gradebook(0)`.

**Comment by rishipudipeddi** [comment]
This gives me the data for all the assignments ever assigned in the current reporting period. How do I just get the grades i.e [{ 'Gifted Algebra 1', 'mark: a']} like you were able to do in 1.3.2

**Comment by kaijchang** [comment]
There is no way to only get the grades, but the grades are included in the data from `sv.get_gradebook()`.

**Comment by rishipudipeddi** [comment]
@kajchang That data is crazy long, so is there a way to extract just the courses, grades, and percentages from it?

**Comment by kaijchang** [comment]
Why does the data length matter if you can just get the sections from it?

**Comment by rishipudipeddi** [comment]
@kajchang The docs do not provide information on how to just get that information. Also I'm not the best at manipulating JSON or XML. I just want to know how to get those pieces of information

**Comment by kaijchang** [comment]
I will definitely work on creating the documentation for the return formats of the API. 2.0.0+ provides way more complicated data and it provides that data more quickly, but also feel free to stay on 1.3.2 and use that if you're more comfortable with that. (to revert to 1.3.2 you should be able to run `pip install studentvue==1.3.2`)

For now, try
```python
gradebook = sv.get_gradebook()
courses = gradebook['Gradebook']['Courses']['Course']
for course in courses:
    name = course['@Title']
    letter_grade = course['Marks']['Mark']['@CalculatedScoreString']
    raw_score = course['Marks']['Mark']['@CalculatedScoreRaw']
    print(name, letter_grade, raw_score)
```
this should get the same data as before
```
AP Comp Sci A A (CMSC350A) A 100.0
AP Physics 1A (PHYS354A) A 96.15
AP Environ Sci A (ENSC350A) A 104.0
AP US History A (USHI350A) A 90.1
AP EngLngComp74 A (ELAC304A) A 94.9
Pre-Calc A H (PCAL250A) A 92.5
```

Also, the data is really complex and what I do is use a website like [this](http://jsonviewer.stack.hu/) to visually explore the JSON to find the parts that I need.

Thanks for your interest in this project!

**Comment by rishipudipeddi** [comment]
Thank you so much for your help

**Comment by rishipudipeddi** [comment]
@kajchang Hmm, I just realized the data I receive from that is from the last report card and not the current grades

**Comment by kaijchang** [comment]
Do you have the app on your phone? It should display the same grades that are displayed in the app.

**Comment by rishipudipeddi** [comment]
@kajchang I have the app on my phone, and it shows my current grades. On the end of last semester, I had a 98.8 in orchestra. That's what the data displays, when in reality I have a 100 in orchestra right now

**Comment by kaijchang** [comment]
You can fetch grades for a specific reporting period
```python
gradebook = sv.get_gradebook()
reporting_periods = gradebook['Gradebook']['ReportingPeriods']['ReportPeriod']

for reporting_period in reporting_periods:
    index = reporting_period['@Index']
    period_name = reporting_period['@GradePeriod']
    start_date = reporting_period['@StartDate']
    end_date = reporting_period['@EndDate']
    print(index, period_name, start_date + ' - ' + end_date)
```

```
0 P1 8/19/2019 - 9/27/2019
1 P2 9/28/2019 - 11/8/2019
2 P3/Fall 11/9/2019 - 12/20/2019
3 P4 12/21/2019 - 2/21/2020
4 P5 2/22/2020 - 4/17/2020
5 P6/Spring 4/18/2020 - 6/2/2020
```

Then you can use the `index` number as an argument to `get_gradebook` to get grades for that specific period. For example, calling `sv.get_gradebook(3)` would get P4 grades for me.

**Comment by rishipudipeddi** [comment]
@kajchang Attempting to run that give me this error:
![image](https://user-images.githubusercontent.com/49598383/77674496-ec3d7300-6f48-11ea-862d-9fa04e73e400.png)

**Comment by kaijchang** [comment]
do you have this line of code `reporting_periods = gradebook['Gradebook']['ReportingPeriods']['ReportPeriod']`

**Comment by rishipudipeddi** [comment]
Hah I didn't. Everything works fine now. Thanks so much for your help. I know I was a pain

**Comment by kaijchang** [comment]
@thexpiredpear found the bug that made it so it didn't return the current reporting period's grades. Upgrading to v2.0.2 should fix it. Sorry!
