### ISSUE TITLE
district_domain drops path when user provides scheme

### ISSUE THREAD

**Issue by thiccaxe** [kajchang/StudentVue#19]
https://github.com/StudentVue/StudentVue.py/blob/002dc48424bf892e8f6d6c0c84c87c8b44a31eaa/studentvue/StudentVue.py#L52-L57

this code (improperly?) drops the path when `district_domain` is prefixed with a scheme such as `https://`, as noted in #18

**Comment by kaijchang** [comment]
Fixed by #20.
