### ISSUE TITLE
Fetching grades and assignments

### ISSUE THREAD

**Issue by kaijchang** [kajchang/StudentVue#3]
This is an essential feature for this library to be more useful. This feature takes a little more investigative work to implement as this info is loaded using a pretty complex request that I started working on here:
https://github.com/kajchang/StudentVue/blob/09c7f30d1e058357e01ef456ab36ddc0f93f8b7f/studentvue/studentvue.py#L135-L160

@LoganMD is looking into this a little at the moment.

**Comment by tetraoxygen** [comment]
My school year doesn't start until the 9th, but I'd love to help with this however else would be useful until then.

**Comment by kaijchang** [comment]
I added grade fetching for your current grade, but I have to look into it more in the future to do it for specific grading periods.

**Comment by kaijchang** [comment]
You can get assignments by posting to `https://[insert domain]/PXP2_Calendar.aspx?AGU=0` and changing the `LB` parameter to the desired month. I'm going to work on it within the next few days. I also want to start making the code more readable soon so it's easier to contribute to.
