### ISSUE TITLE
Feature Request - Get due date of assignment

### ISSUE THREAD

**Issue by Whodiduexpect** [kajchang/StudentVue#4]
Currently, from reading the function ```get_assignments```, there seem to be 4 attributes. Those are:
```
assignment_id
class_
grading_period
name
```
However, I don't see any way to get the due date of an assignment. Am I missing something, or was this not added? I find this to be a pretty crucial feature.

**Comment by kaijchang** [comment]
This was already added in v1.2.3. https://github.com/kajchang/StudentVue/commit/41ddd9715b75fd7b5e545a9bed9ad80bd04fbc70
