### ISSUE TITLE
Parsing error when elements do not exist

### ISSUE THREAD

**Issue by Whodiduexpect** [kajchang/StudentVue#5]
When I try to login, I get this traceback.
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\user\AppData\Local\Programs\Python\Python36\lib\site-packages\studentvue\studentvue.py", line 56, in __init__
    home_page.find(alt='Student Photo')['src']).group(1)
AttributeError: 'NoneType' object has no attribute 'group'
```
It seems to be related to parsing the student photo as there is none linked in Student Vue. I have confirmed that it works perfectly fine if I remove this from studentvue.py:
```
self.picture_url = 'https://{}/{}'.format(self.district_domain,
                                                  home_page.find(alt='Student Photo')['src'])
```

**Comment by kaijchang** [comment]
@Whodiduexpect The seems to actually be from the next line,
https://github.com/kajchang/StudentVue/blob/153bbcba1d987887cd7b1c8d0888dc601d03b082/studentvue/studentvue.py#L58-L59
To clarify, if you inspect element on your photo, what is the element's `src`?

**Comment by Whodiduexpect** [comment]
Yes, you are correct. I copied the wrong line. The element of the picture not found is  ```<img alt="Student Photo" src="Images/PXP/NoPhoto.png" width="40" height="50">```

**Comment by Whodiduexpect** [comment]
Also, when I re-ran it with line 58 removed, I ran into another problem that didn't happen before. When it checks for the schedule, it checks the url ```https://(portal)/PXP2_ClassSchedule.aspx?AGU=0```. However, on my portal, that currently defaults to semester 2 giving a webpage that says: 
> Class Schedule data not available for this school

To fix that on my portal, it would have to check ```https://(portal)/PXP2_ClassSchedule.aspx?AGU=0&VDT=0```, which is equivalent to selecting the Semester 1 option.<br>
And if you're wondering what the traceback is when it tries to use the schedule data:
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\user\AppData\Local\Programs\Python\Python36\lib\site-packages\studentvue\studentvue.py", line 56, in __init__
    def get_schedule(self):
AttributeError: 'NoneType' object has no attribute 'group
'```

**Comment by kaijchang** [comment]
Can you test out if these fixes work by installing from the branch: `pip3 install git+https://github.com/kajchang/StudentVue.git@simplify-code`.

**Comment by Whodiduexpect** [comment]
Looks like there's an indent issue...
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\user\AppData\Local\Programs\Python\Python36\lib\site-packages\studentvue\__init__.py", line 1, in <module>
    from .studentvue import StudentVue
  File "C:\Users\user\AppData\Local\Programs\Python\Python36\lib\site-packages\studentvue\studentvue.py", line 52
    self.picture_url = 'https://{}/{}'.format(self.district_domain,
    ^
IndentationError: unexpected indent
```

**Comment by kaijchang** [comment]
I think it's an error on your end somehow, because I can import it on my computer and it passes https://travis-ci.com/kajchang/StudentVue/builds/126313188.

**Comment by Whodiduexpect** [comment]
Turns out pip had some issues overwriting the current package, so I needed to delete it before reinstalling it. Yes, it works perfectly!

**Comment by kaijchang** [comment]
Cool, I will merge the fixes.
