### ISSUE TITLE
PyPI doesn't have latest version

### ISSUE THREAD

**Issue by Whodiduexpect** [kajchang/StudentVue#9]
Since the version number hasn't changed, PyPI still has the version before commit https://github.com/kajchang/StudentVue/commit/4cefe09eaebbf24b7b7bfe026b17efa5809648b1. I can verify this because I trigger the edge case where there is no photo linked (fixed in commit https://github.com/kajchang/StudentVue/commit/4cefe09eaebbf24b7b7bfe026b17efa5809648b1 obviously).

If I try to install it via pip
```
pip3 install studentvue (or) pip3 install studentvue==1.2.3.1
```
And when I try it...
```py
Traceback (most recent call last):
  File "/home/user/.local/lib/python3.6/site-packages/studentvue/studentvue.py", line 56, in __init__
    home_page.find(alt='Student Photo')['src']).group(1)
```
If I clone the repository manually
```
git clone https://github.com/kajchang/StudentVue
cd StudentVue
python3 setup.py install
```
It then proceeds to work as expected. 

Also, I just realized that the last updated date on PyPI is 3 days before that commit, which would already mean that the version hosted is out-of-date...

**Comment by kaijchang** [comment]
Bumped version to `1.2.4`.
